# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created: Fri Dec  9 12:49:54 2011
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1090, 621)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Bond Raper", None, QtGui.QApplication.UnicodeUTF8))
        Form.setAutoFillBackground(False)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 1071, 541))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.scrollArea = QtGui.QScrollArea(self.layoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1065, 485))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.changeTable = QtGui.QTableWidget(self.scrollAreaWidgetContents)
        self.changeTable.setGeometry(QtCore.QRect(0, 0, 1051, 421))
        self.changeTable.setRowCount(14)
        self.changeTable.setColumnCount(10)
        self.changeTable.setObjectName(_fromUtf8("changeTable"))
        self.label_15 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setGeometry(QtCore.QRect(0, 440, 151, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setText(QtGui.QApplication.translate("Form", "VaR - Credit Spread:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_19 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setGeometry(QtCore.QRect(460, 486, 1069, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setText(QtGui.QApplication.translate("Form", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_18 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setGeometry(QtCore.QRect(0, 420, 141, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setText(QtGui.QApplication.translate("Form", "VaR - Interest Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_16 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setGeometry(QtCore.QRect(0, 460, 141, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setText(QtGui.QApplication.translate("Form", "VaR - Total:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.varIR = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.varIR.setGeometry(QtCore.QRect(190, 420, 31, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.varIR.setFont(font)
        self.varIR.setText(QtGui.QApplication.translate("Form", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.varIR.setTextFormat(QtCore.Qt.PlainText)
        self.varIR.setObjectName(_fromUtf8("varIR"))
        self.varCS = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.varCS.setGeometry(QtCore.QRect(190, 440, 31, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.varCS.setFont(font)
        self.varCS.setText(QtGui.QApplication.translate("Form", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.varCS.setTextFormat(QtCore.Qt.PlainText)
        self.varCS.setObjectName(_fromUtf8("varCS"))
        self.varTotal = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.varTotal.setGeometry(QtCore.QRect(190, 460, 31, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.varTotal.setFont(font)
        self.varTotal.setText(QtGui.QApplication.translate("Form", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.varTotal.setTextFormat(QtCore.Qt.PlainText)
        self.varTotal.setObjectName(_fromUtf8("varTotal"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.clientTime = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.clientTime.setFont(font)
        self.clientTime.setText(QtGui.QApplication.translate("Form", "Client Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.clientTime.setObjectName(_fromUtf8("clientTime"))
        self.verticalLayout_2.addWidget(self.clientTime)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.serverTime = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.serverTime.setFont(font)
        self.serverTime.setText(QtGui.QApplication.translate("Form", "Server Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.serverTime.setObjectName(_fromUtf8("serverTime"))
        self.horizontalLayout_4.addWidget(self.serverTime)
        self.realTime = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.realTime.setFont(font)
        self.realTime.setText(QtGui.QApplication.translate("Form", "Real:", None, QtGui.QApplication.UnicodeUTF8))
        self.realTime.setObjectName(_fromUtf8("realTime"))
        self.horizontalLayout_4.addWidget(self.realTime)
        self.userTime = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.userTime.setFont(font)
        self.userTime.setText(QtGui.QApplication.translate("Form", "User:", None, QtGui.QApplication.UnicodeUTF8))
        self.userTime.setObjectName(_fromUtf8("userTime"))
        self.horizontalLayout_4.addWidget(self.userTime)
        self.systemTime = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.systemTime.setFont(font)
        self.systemTime.setText(QtGui.QApplication.translate("Form", "System:", None, QtGui.QApplication.UnicodeUTF8))
        self.systemTime.setObjectName(_fromUtf8("systemTime"))
        self.horizontalLayout_4.addWidget(self.systemTime)
        self.userSystemTime = QtGui.QLabel(self.layoutWidget)
        self.userSystemTime.setText(QtGui.QApplication.translate("Form", "User + System:", None, QtGui.QApplication.UnicodeUTF8))
        self.userSystemTime.setObjectName(_fromUtf8("userSystemTime"))
        self.horizontalLayout_4.addWidget(self.userSystemTime)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(140, 0, 291, 20))
        self.label.setStyleSheet(_fromUtf8("border: 1px solid black;\n"
"background-color: #99FF80;"))
        self.label.setText(QtGui.QApplication.translate("Form", "Opening Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(440, 0, 291, 20))
        self.label_2.setStyleSheet(_fromUtf8("border: 1px solid black;\n"
"background-color: #FFCC00;"))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Closing Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(750, 0, 281, 20))
        self.label_3.setStyleSheet(_fromUtf8("border: 1px solid black;\n"
"background-color: #BFFFFF;"))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Intra-day Change", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.riskTable = QtGui.QTableWidget(self.tab_2)
        self.riskTable.setGeometry(QtCore.QRect(10, 20, 931, 361))
        self.riskTable.setRowCount(11)
        self.riskTable.setColumnCount(9)
        self.riskTable.setObjectName(_fromUtf8("riskTable"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(140, 0, 191, 20))
        self.label_4.setStyleSheet(_fromUtf8("border: 1px solid black;\n"
"background-color: #99FF80;"))
        self.label_4.setText(QtGui.QApplication.translate("Form", "2 YR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(340, 0, 191, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(_fromUtf8("border: 1px solid black;\n"
"background-color: #FFCC00;"))
        self.label_5.setText(QtGui.QApplication.translate("Form", "5 YR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(540, 0, 191, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("border: 1px solid black;\n"
"background-color: #BFFFFF;"))
        self.label_6.setText(QtGui.QApplication.translate("Form", "10 YR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(740, 0, 191, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(_fromUtf8("border: 1px solid black;\n"
"background-color: #FF8080;"))
        self.label_7.setText(QtGui.QApplication.translate("Form", "30 YR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        self.changeTable.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Daily Change", None, QtGui.QApplication.UnicodeUTF8))
        self.riskTable.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Risk", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

