# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created: Mon Dec 12 15:27:09 2011
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!
import socket
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1090, 621)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Bond Raper", None, QtGui.QApplication.UnicodeUTF8))
        Form.setAutoFillBackground(False)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.changeTable = QtGui.QTableWidget(self.tab)
        self.changeTable.setGeometry(QtCore.QRect(0, 0, 1061, 441))
        self.changeTable.setRowCount(16)
        self.changeTable.setColumnCount(10)
        self.changeTable.setObjectName(_fromUtf8("changeTable"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 450, 1051, 113))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.varTotal = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.varTotal.setFont(font)
        self.varTotal.setText(QtGui.QApplication.translate("Form", "VaR - Total:", None, QtGui.QApplication.UnicodeUTF8))
        self.varTotal.setObjectName(_fromUtf8("varTotal"))
        self.verticalLayout_2.addWidget(self.varTotal)
        self.varIR = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.varIR.setFont(font)
        self.varIR.setText(QtGui.QApplication.translate("Form", "VaR - Interest Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.varIR.setObjectName(_fromUtf8("varIR"))
        self.verticalLayout_2.addWidget(self.varIR)
        self.varCS = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.varCS.setFont(font)
        self.varCS.setText(QtGui.QApplication.translate("Form", "VaR - Credit Spread:", None, QtGui.QApplication.UnicodeUTF8))
        self.varCS.setObjectName(_fromUtf8("varCS"))
        self.verticalLayout_2.addWidget(self.varCS)
        self.clientTime = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.clientTime.setFont(font)
        self.clientTime.setText(QtGui.QApplication.translate("Form", "Client Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.clientTime.setObjectName(_fromUtf8("clientTime"))
        self.verticalLayout_2.addWidget(self.clientTime)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.serverTime = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.serverTime.setFont(font)
        self.serverTime.setText(QtGui.QApplication.translate("Form", "Server Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.serverTime.setObjectName(_fromUtf8("serverTime"))
        self.horizontalLayout_4.addWidget(self.serverTime)
        self.realTime = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.realTime.setFont(font)
        self.realTime.setText(QtGui.QApplication.translate("Form", "Real:", None, QtGui.QApplication.UnicodeUTF8))
        self.realTime.setObjectName(_fromUtf8("realTime"))
        self.horizontalLayout_4.addWidget(self.realTime)
        self.userTime = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.userTime.setFont(font)
        self.userTime.setText(QtGui.QApplication.translate("Form", "User:", None, QtGui.QApplication.UnicodeUTF8))
        self.userTime.setObjectName(_fromUtf8("userTime"))
        self.horizontalLayout_4.addWidget(self.userTime)
        self.systemTime = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.systemTime.setFont(font)
        self.systemTime.setText(QtGui.QApplication.translate("Form", "System:", None, QtGui.QApplication.UnicodeUTF8))
        self.systemTime.setObjectName(_fromUtf8("systemTime"))
        self.horizontalLayout_4.addWidget(self.systemTime)
        self.userSystemTime = QtGui.QLabel(self.layoutWidget_2)
        self.userSystemTime.setText(QtGui.QApplication.translate("Form", "User + System:", None, QtGui.QApplication.UnicodeUTF8))
        self.userSystemTime.setObjectName(_fromUtf8("userSystemTime"))
        self.horizontalLayout_4.addWidget(self.userSystemTime)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.riskTable = QtGui.QTableWidget(self.tab_2)
        self.riskTable.setGeometry(QtCore.QRect(0, 0, 1061, 375))
        self.riskTable.setRowCount(11)
        self.riskTable.setColumnCount(9)
        self.riskTable.setObjectName(_fromUtf8("riskTable"))
        self.layoutWidget_3 = QtGui.QWidget(self.tab_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 540, 1041, 20))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.serverTime_2 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.serverTime_2.setFont(font)
        self.serverTime_2.setText(QtGui.QApplication.translate("Form", "Server Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.serverTime_2.setObjectName(_fromUtf8("serverTime_2"))
        self.horizontalLayout_5.addWidget(self.serverTime_2)
        self.realTime_2 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.realTime_2.setFont(font)
        self.realTime_2.setText(QtGui.QApplication.translate("Form", "Real:", None, QtGui.QApplication.UnicodeUTF8))
        self.realTime_2.setObjectName(_fromUtf8("realTime_2"))
        self.horizontalLayout_5.addWidget(self.realTime_2)
        self.userTime_2 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.userTime_2.setFont(font)
        self.userTime_2.setText(QtGui.QApplication.translate("Form", "User:", None, QtGui.QApplication.UnicodeUTF8))
        self.userTime_2.setObjectName(_fromUtf8("userTime_2"))
        self.horizontalLayout_5.addWidget(self.userTime_2)
        self.systemTime_2 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.systemTime_2.setFont(font)
        self.systemTime_2.setText(QtGui.QApplication.translate("Form", "System:", None, QtGui.QApplication.UnicodeUTF8))
        self.systemTime_2.setObjectName(_fromUtf8("systemTime_2"))
        self.horizontalLayout_5.addWidget(self.systemTime_2)
        self.userSystemTime_2 = QtGui.QLabel(self.layoutWidget_3)
        self.userSystemTime_2.setText(QtGui.QApplication.translate("Form", "User + System:", None, QtGui.QApplication.UnicodeUTF8))
        self.userSystemTime_2.setObjectName(_fromUtf8("userSystemTime_2"))
        self.horizontalLayout_5.addWidget(self.userSystemTime_2)
        self.clientTime_2 = QtGui.QLabel(self.tab_2)
        self.clientTime_2.setGeometry(QtCore.QRect(0, 520, 1067, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.clientTime_2.setFont(font)
        self.clientTime_2.setText(QtGui.QApplication.translate("Form", "Client Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.clientTime_2.setObjectName(_fromUtf8("clientTime_2"))
        self.shiftUp = QtGui.QPushButton(self.tab_2)
        self.shiftUp.setGeometry(QtCore.QRect(50, 390, 325, 27))
        self.shiftUp.setText(QtGui.QApplication.translate("Form", "Shift Up 50%", None, QtGui.QApplication.UnicodeUTF8))
        self.shiftUp.setObjectName(_fromUtf8("shiftUp"))
        self.shiftDown = QtGui.QPushButton(self.tab_2)
        self.shiftDown.setGeometry(QtCore.QRect(380, 390, 325, 27))
        self.shiftDown.setText(QtGui.QApplication.translate("Form", "Shift Down 50%", None, QtGui.QApplication.UnicodeUTF8))
        self.shiftDown.setObjectName(_fromUtf8("shiftDown"))
        self.reset = QtGui.QPushButton(self.tab_2)
        self.reset.setGeometry(QtCore.QRect(710, 390, 325, 27))
        self.reset.setText(QtGui.QApplication.translate("Form", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.reset.setObjectName(_fromUtf8("reset"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
    def initializeTable(self):
        #Setting Change Table
        #Header Row
        #Opening Pos- Closing Pos - Intra-day Change
        self.changeTable.setSpan(0, 1, 1, 3)
        self.changeTable.setSpan(0, 4, 1, 3)
        self.changeTable.setSpan(0, 7, 1, 3)
        op = QtGui.QTableWidgetItem("Opening Position")
        op.setBackgroundColor(QtGui.QColor(153,255,128))
        op.setTextAlignment(QtCore.Qt.AlignCenter)
        self.changeTable.setItem(0,1,op)
        cp = QtGui.QTableWidgetItem("Closing Position")
        cp.setBackgroundColor(QtGui.QColor(255,204,0))
        cp.setTextAlignment(QtCore.Qt.AlignCenter)
        self.changeTable.setItem(0,4,cp)
        idc = QtGui.QTableWidgetItem("Intra-day Change")
        idc.setBackgroundColor(QtGui.QColor(191,255,255))
        idc.setTextAlignment(QtCore.Qt.AlignCenter)
        self.changeTable.setItem(0,7,idc)
        #Ticker - notional - risk - lgd - x3
        ticker = QtGui.QTableWidgetItem("Ticker")
        self.changeTable.setItem(1,0,ticker)
        n1 = QtGui.QTableWidgetItem("Notional")
        self.changeTable.setItem(1,1,n1)
        r1 = QtGui.QTableWidgetItem("Risk")
        self.changeTable.setItem(1,2,r1)
        l1 = QtGui.QTableWidgetItem("LGD")
        self.changeTable.setItem(1,3,l1)
        n2 = QtGui.QTableWidgetItem("Notional")
        self.changeTable.setItem(1,4,n2)
        r2 = QtGui.QTableWidgetItem("Risk")
        self.changeTable.setItem(1,5,r2)
        l2 = QtGui.QTableWidgetItem("LGD")
        self.changeTable.setItem(1,6,l2)
        n3 = QtGui.QTableWidgetItem("Notional")
        self.changeTable.setItem(1,7,n3)
        r3 = QtGui.QTableWidgetItem("Risk")
        self.changeTable.setItem(1,8,r3)
        l3 = QtGui.QTableWidgetItem("LGD")
        self.changeTable.setItem(1,9,l3)
        #Header Col
        temp = QtGui.QTableWidgetItem("EX.")
        self.changeTable.setItem(2,0,temp)
        
        A = QtGui.QTableWidgetItem("A")
        self.changeTable.setItem(4,0,A)
        AA = QtGui.QTableWidgetItem("AA")
        self.changeTable.setItem(5,0,AA)
        AAA = QtGui.QTableWidgetItem("AAA")
        self.changeTable.setItem(6,0,AAA)
        B = QtGui.QTableWidgetItem("B")
        self.changeTable.setItem(7,0,B)
        BB = QtGui.QTableWidgetItem("BB")
        self.changeTable.setItem(8,0,BB)
        BBB = QtGui.QTableWidgetItem("BBB")
        self.changeTable.setItem(9,0,BBB)
        C = QtGui.QTableWidgetItem("C")
        self.changeTable.setItem(10,0,C)
        CC = QtGui.QTableWidgetItem("CC")
        self.changeTable.setItem(11,0,CC)
        CCC = QtGui.QTableWidgetItem("CCC")
        self.changeTable.setItem(12,0,CCC)
        
        ig = QtGui.QTableWidgetItem("Investment Grade")
        self.changeTable.setItem(14,0,ig)
        junk = QtGui.QTableWidgetItem("Junk")
        self.changeTable.setItem(15,0,junk)

        #Setting Risk Table
        self.riskTable.setColumnWidth(0, 150)
        #2YR - 5YR - 10YR - 30YR
        self.riskTable.setSpan(0, 1, 1, 2)
        self.riskTable.setSpan(0, 3, 1, 2)
        self.riskTable.setSpan(0, 5, 1, 2)
        self.riskTable.setSpan(0, 7, 1, 2)
        
        #Vertical Header
        closingPos = QtGui.QTableWidgetItem("Closing Position")
        closingPos.setTextAlignment(QtCore.Qt.AlignVCenter)
        self.riskTable.setItem(3, 0, closingPos)
        twoYRHedge = QtGui.QTableWidgetItem("2 YR Hedge")
        twoYRHedge.setTextAlignment(QtCore.Qt.AlignVCenter)
        self.riskTable.setItem(4, 0, twoYRHedge)
        
        shiftedPos = QtGui.QTableWidgetItem("Shifted Position")
        shiftedPos.setTextAlignment(QtCore.Qt.AlignVCenter)
        self.riskTable.setItem(6, 0, shiftedPos)
        shiftedTwoYRHedge = QtGui.QTableWidgetItem("Shifted 2 YR Hedge")
        shiftedTwoYRHedge.setTextAlignment(QtCore.Qt.AlignVCenter)
        self.riskTable.setItem(7, 0, shiftedTwoYRHedge)
        
        yc = QtGui.QTableWidgetItem("Yield Curve")
        yc.setTextAlignment(QtCore.Qt.AlignVCenter)
        self.riskTable.setItem(9, 0, yc)
        bc = QtGui.QTableWidgetItem("Bump Curve")
        bc.setTextAlignment(QtCore.Qt.AlignVCenter)
        self.riskTable.setItem(10, 0, bc)
        #Changing Background Color of Non-Changeable Slots
        bc0 = QtGui.QTableWidgetItem("")
        bc0.setBackgroundColor(QtGui.QColor(238,233,233))
        self.riskTable.setItem(10,1,bc0)
        yc0 = QtGui.QTableWidgetItem("")
        yc0.setBackgroundColor(QtGui.QColor(238,233,233))
        self.riskTable.setItem(9,1,yc0)
        gry0 = QtGui.QTableWidgetItem("")
        gry0.setBackgroundColor(QtGui.QColor(238,233,233))
        self.riskTable.setItem(10,3,gry0)
        gry1 = QtGui.QTableWidgetItem("")
        gry1.setBackgroundColor(QtGui.QColor(238,233,233))
        self.riskTable.setItem(9,3,gry1)
        gry2 = QtGui.QTableWidgetItem("")
        gry2.setBackgroundColor(QtGui.QColor(238,233,233))
        self.riskTable.setItem(10,5,gry2)
        gry3 = QtGui.QTableWidgetItem("")
        gry3.setBackgroundColor(QtGui.QColor(238,233,233))
        self.riskTable.setItem(9,5,gry3)
        gry4 = QtGui.QTableWidgetItem("")
        gry4.setBackgroundColor(QtGui.QColor(238,233,233))
        self.riskTable.setItem(10,7,gry4)
        gry5 = QtGui.QTableWidgetItem("")
        gry5.setBackgroundColor(QtGui.QColor(238,233,233))
        self.riskTable.setItem(9,7,gry5)
        #Setting Changable Slots to 0
        bc1 = QtGui.QTableWidgetItem("0")
        bc1.setTextAlignment(QtCore.Qt.AlignCenter)
        self.riskTable.setItem(10,2,bc1)
        bc2 = QtGui.QTableWidgetItem("0")
        bc2.setTextAlignment(QtCore.Qt.AlignCenter)
        self.riskTable.setItem(10,4,bc2)
        bc3 = QtGui.QTableWidgetItem("0")
        bc3.setTextAlignment(QtCore.Qt.AlignCenter)
        self.riskTable.setItem(10,6,bc3)
        bc4 = QtGui.QTableWidgetItem("0")
        bc4.setTextAlignment(QtCore.Qt.AlignCenter)
        self.riskTable.setItem(10,8,bc4)
        
        #Horizontal Header
        twoYR = QtGui.QTableWidgetItem("2 YR")
        twoYR.setBackgroundColor(QtGui.QColor(255,204,0))
        twoYR.setTextAlignment(QtCore.Qt.AlignCenter)
        self.riskTable.setItem(0, 1, twoYR)
        
        fiveYR = QtGui.QTableWidgetItem("5 YR")
        fiveYR.setBackgroundColor(QtGui.QColor(191,255,255))
        fiveYR.setTextAlignment(QtCore.Qt.AlignCenter)
        self.riskTable.setItem(0, 3, fiveYR)
        
        tenYR = QtGui.QTableWidgetItem("10 YR")
        tenYR.setBackgroundColor(QtGui.QColor(255,128,128))
        tenYR.setTextAlignment(QtCore.Qt.AlignCenter)
        self.riskTable.setItem(0, 5, tenYR)
        
        thirtyYR = QtGui.QTableWidgetItem("30 YR")
        thirtyYR.setBackgroundColor(QtGui.QColor(153,255,128))
        thirtyYR.setTextAlignment(QtCore.Qt.AlignCenter)
        self.riskTable.setItem(0, 7, thirtyYR)
        
        book = QtGui.QTableWidgetItem("Book")
        book.setTextAlignment(QtCore.Qt.AlignCenter)
        self.riskTable.setItem(1,0,book)
        risk2 = QtGui.QTableWidgetItem("Risk")
        risk2.setTextAlignment(QtCore.Qt.AlignCenter)
        self.riskTable.setItem(1,1,risk2)
        mv2 = QtGui.QTableWidgetItem("Market Val")
        mv2.setTextAlignment(QtCore.Qt.AlignCenter)
        self.riskTable.setItem(1,2,mv2)
        risk5 = QtGui.QTableWidgetItem("Risk")
        risk5.setTextAlignment(QtCore.Qt.AlignCenter)
        self.riskTable.setItem(1,3,risk5)
        mv5 = QtGui.QTableWidgetItem("Market Val")
        mv5.setTextAlignment(QtCore.Qt.AlignCenter)
        self.riskTable.setItem(1,4,mv5)
        risk10 = QtGui.QTableWidgetItem("Risk")
        risk10.setTextAlignment(QtCore.Qt.AlignCenter)
        self.riskTable.setItem(1,5,risk10)
        mv10 = QtGui.QTableWidgetItem("Market Val")
        mv10.setTextAlignment(QtCore.Qt.AlignCenter)
        self.riskTable.setItem(1,6,mv10)
        risk30 = QtGui.QTableWidgetItem("Risk")
        risk30.setTextAlignment(QtCore.Qt.AlignCenter)
        self.riskTable.setItem(1,7,risk30)
        mv30 = QtGui.QTableWidgetItem("Market Val")
        mv30.setTextAlignment(QtCore.Qt.AlignCenter)
        self.riskTable.setItem(1,8,mv30)

    def retranslateUi(self, Form):
        self.changeTable.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Daily Change", None, QtGui.QApplication.UnicodeUTF8))
        self.riskTable.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Risk", None, QtGui.QApplication.UnicodeUTF8))
    
    def loadPortfolio(self):
        HOST = socket.gethostname()
        PORT = 0x1234
        MSGSIZE = 8192
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.connect((HOST, PORT))
        var = "loadticker";
        s.send(var)
        data = s.recv(MSGSIZE)
        stringshit = repr(data)
        test = QtGui.QTableWidgetItem(stringshit)
        self.changeTable.setItem(1,1, test)
        s.close()

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    ui.initializeTable()
    ui.loadPortfolio()
    Form.show()
    sys.exit(app.exec_())

