# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created: Mon Dec 12 20:56:05 2011
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1090, 640)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Bond Raper", None, QtGui.QApplication.UnicodeUTF8))
        Form.setAutoFillBackground(False)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.changeTable = QtGui.QTableWidget(self.tab)
        self.changeTable.setGeometry(QtCore.QRect(0, 0, 1061, 441))
        self.changeTable.setRowCount(16)
        self.changeTable.setColumnCount(10)
        self.changeTable.setObjectName(_fromUtf8("changeTable"))
        self.clientTime = QtGui.QLabel(self.tab)
        self.clientTime.setGeometry(QtCore.QRect(1, 535, 88, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.clientTime.setFont(font)
        self.clientTime.setText(QtGui.QApplication.translate("Form", "Client Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.clientTime.setObjectName(_fromUtf8("clientTime"))
        self.widget = QtGui.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(2, 564, 1041, 19))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.serverTime = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.serverTime.setFont(font)
        self.serverTime.setText(QtGui.QApplication.translate("Form", "Server Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.serverTime.setObjectName(_fromUtf8("serverTime"))
        self.horizontalLayout.addWidget(self.serverTime)
        self.realTime = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.realTime.setFont(font)
        self.realTime.setText(QtGui.QApplication.translate("Form", "Real:", None, QtGui.QApplication.UnicodeUTF8))
        self.realTime.setObjectName(_fromUtf8("realTime"))
        self.horizontalLayout.addWidget(self.realTime)
        self.userTime = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.userTime.setFont(font)
        self.userTime.setText(QtGui.QApplication.translate("Form", "User:", None, QtGui.QApplication.UnicodeUTF8))
        self.userTime.setObjectName(_fromUtf8("userTime"))
        self.horizontalLayout.addWidget(self.userTime)
        self.systemTime = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.systemTime.setFont(font)
        self.systemTime.setText(QtGui.QApplication.translate("Form", "System:", None, QtGui.QApplication.UnicodeUTF8))
        self.systemTime.setObjectName(_fromUtf8("systemTime"))
        self.horizontalLayout.addWidget(self.systemTime)
        self.userSystemTime = QtGui.QLabel(self.widget)
        self.userSystemTime.setText(QtGui.QApplication.translate("Form", "User + System:", None, QtGui.QApplication.UnicodeUTF8))
        self.userSystemTime.setObjectName(_fromUtf8("userSystemTime"))
        self.horizontalLayout.addWidget(self.userSystemTime)
        self.widget1 = QtGui.QWidget(self.tab)
        self.widget1.setGeometry(QtCore.QRect(1, 450, 1041, 19))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.varTotal = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.varTotal.setFont(font)
        self.varTotal.setText(QtGui.QApplication.translate("Form", "VaR - Total:", None, QtGui.QApplication.UnicodeUTF8))
        self.varTotal.setObjectName(_fromUtf8("varTotal"))
        self.horizontalLayout_2.addWidget(self.varTotal)
        self.vt1 = QtGui.QLabel(self.widget1)
        self.vt1.setText(QtGui.QApplication.translate("Form", "opening", None, QtGui.QApplication.UnicodeUTF8))
        self.vt1.setTextFormat(QtCore.Qt.PlainText)
        self.vt1.setObjectName(_fromUtf8("vt1"))
        self.horizontalLayout_2.addWidget(self.vt1)
        self.vt2 = QtGui.QLabel(self.widget1)
        self.vt2.setText(QtGui.QApplication.translate("Form", "opening", None, QtGui.QApplication.UnicodeUTF8))
        self.vt2.setTextFormat(QtCore.Qt.PlainText)
        self.vt2.setObjectName(_fromUtf8("vt2"))
        self.horizontalLayout_2.addWidget(self.vt2)
        self.vt3 = QtGui.QLabel(self.widget1)
        self.vt3.setText(QtGui.QApplication.translate("Form", "opening", None, QtGui.QApplication.UnicodeUTF8))
        self.vt3.setTextFormat(QtCore.Qt.PlainText)
        self.vt3.setObjectName(_fromUtf8("vt3"))
        self.horizontalLayout_2.addWidget(self.vt3)
        self.widget2 = QtGui.QWidget(self.tab)
        self.widget2.setGeometry(QtCore.QRect(1, 507, 1041, 19))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.varCS = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.varCS.setFont(font)
        self.varCS.setText(QtGui.QApplication.translate("Form", "VaR - Credit Spread:", None, QtGui.QApplication.UnicodeUTF8))
        self.varCS.setObjectName(_fromUtf8("varCS"))
        self.horizontalLayout_3.addWidget(self.varCS)
        self.vc1 = QtGui.QLabel(self.widget2)
        self.vc1.setText(QtGui.QApplication.translate("Form", "opening", None, QtGui.QApplication.UnicodeUTF8))
        self.vc1.setTextFormat(QtCore.Qt.PlainText)
        self.vc1.setObjectName(_fromUtf8("vc1"))
        self.horizontalLayout_3.addWidget(self.vc1)
        self.vc2 = QtGui.QLabel(self.widget2)
        self.vc2.setText(QtGui.QApplication.translate("Form", "opening", None, QtGui.QApplication.UnicodeUTF8))
        self.vc2.setTextFormat(QtCore.Qt.PlainText)
        self.vc2.setObjectName(_fromUtf8("vc2"))
        self.horizontalLayout_3.addWidget(self.vc2)
        self.vc3 = QtGui.QLabel(self.widget2)
        self.vc3.setText(QtGui.QApplication.translate("Form", "opening", None, QtGui.QApplication.UnicodeUTF8))
        self.vc3.setTextFormat(QtCore.Qt.PlainText)
        self.vc3.setObjectName(_fromUtf8("vc3"))
        self.horizontalLayout_3.addWidget(self.vc3)
        self.widget3 = QtGui.QWidget(self.tab)
        self.widget3.setGeometry(QtCore.QRect(1, 479, 1041, 19))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.varIR = QtGui.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.varIR.setFont(font)
        self.varIR.setText(QtGui.QApplication.translate("Form", "VaR - Interest Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.varIR.setObjectName(_fromUtf8("varIR"))
        self.horizontalLayout_4.addWidget(self.varIR)
        self.vi1 = QtGui.QLabel(self.widget3)
        self.vi1.setText(QtGui.QApplication.translate("Form", "opening", None, QtGui.QApplication.UnicodeUTF8))
        self.vi1.setTextFormat(QtCore.Qt.PlainText)
        self.vi1.setObjectName(_fromUtf8("vi1"))
        self.horizontalLayout_4.addWidget(self.vi1)
        self.vi2 = QtGui.QLabel(self.widget3)
        self.vi2.setText(QtGui.QApplication.translate("Form", "opening", None, QtGui.QApplication.UnicodeUTF8))
        self.vi2.setTextFormat(QtCore.Qt.PlainText)
        self.vi2.setObjectName(_fromUtf8("vi2"))
        self.horizontalLayout_4.addWidget(self.vi2)
        self.vi3 = QtGui.QLabel(self.widget3)
        self.vi3.setText(QtGui.QApplication.translate("Form", "opening", None, QtGui.QApplication.UnicodeUTF8))
        self.vi3.setTextFormat(QtCore.Qt.PlainText)
        self.vi3.setObjectName(_fromUtf8("vi3"))
        self.horizontalLayout_4.addWidget(self.vi3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.riskTable = QtGui.QTableWidget(self.tab_2)
        self.riskTable.setGeometry(QtCore.QRect(0, 0, 1061, 375))
        self.riskTable.setRowCount(11)
        self.riskTable.setColumnCount(9)
        self.riskTable.setObjectName(_fromUtf8("riskTable"))
        self.layoutWidget_3 = QtGui.QWidget(self.tab_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 570, 1041, 20))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.serverTime_2 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.serverTime_2.setFont(font)
        self.serverTime_2.setText(QtGui.QApplication.translate("Form", "Server Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.serverTime_2.setObjectName(_fromUtf8("serverTime_2"))
        self.horizontalLayout_5.addWidget(self.serverTime_2)
        self.realTime_2 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.realTime_2.setFont(font)
        self.realTime_2.setText(QtGui.QApplication.translate("Form", "Real:", None, QtGui.QApplication.UnicodeUTF8))
        self.realTime_2.setObjectName(_fromUtf8("realTime_2"))
        self.horizontalLayout_5.addWidget(self.realTime_2)
        self.userTime_2 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.userTime_2.setFont(font)
        self.userTime_2.setText(QtGui.QApplication.translate("Form", "User:", None, QtGui.QApplication.UnicodeUTF8))
        self.userTime_2.setObjectName(_fromUtf8("userTime_2"))
        self.horizontalLayout_5.addWidget(self.userTime_2)
        self.systemTime_2 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.systemTime_2.setFont(font)
        self.systemTime_2.setText(QtGui.QApplication.translate("Form", "System:", None, QtGui.QApplication.UnicodeUTF8))
        self.systemTime_2.setObjectName(_fromUtf8("systemTime_2"))
        self.horizontalLayout_5.addWidget(self.systemTime_2)
        self.userSystemTime_2 = QtGui.QLabel(self.layoutWidget_3)
        self.userSystemTime_2.setText(QtGui.QApplication.translate("Form", "User + System:", None, QtGui.QApplication.UnicodeUTF8))
        self.userSystemTime_2.setObjectName(_fromUtf8("userSystemTime_2"))
        self.horizontalLayout_5.addWidget(self.userSystemTime_2)
        self.clientTime_2 = QtGui.QLabel(self.tab_2)
        self.clientTime_2.setGeometry(QtCore.QRect(0, 550, 1067, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.clientTime_2.setFont(font)
        self.clientTime_2.setText(QtGui.QApplication.translate("Form", "Client Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.clientTime_2.setObjectName(_fromUtf8("clientTime_2"))
        self.shiftUp = QtGui.QPushButton(self.tab_2)
        self.shiftUp.setGeometry(QtCore.QRect(50, 390, 325, 27))
        self.shiftUp.setText(QtGui.QApplication.translate("Form", "Shift Up 50%", None, QtGui.QApplication.UnicodeUTF8))
        self.shiftUp.setObjectName(_fromUtf8("shiftUp"))
        self.shiftDown = QtGui.QPushButton(self.tab_2)
        self.shiftDown.setGeometry(QtCore.QRect(380, 390, 325, 27))
        self.shiftDown.setText(QtGui.QApplication.translate("Form", "Shift Down 50%", None, QtGui.QApplication.UnicodeUTF8))
        self.shiftDown.setObjectName(_fromUtf8("shiftDown"))
        self.reset = QtGui.QPushButton(self.tab_2)
        self.reset.setGeometry(QtCore.QRect(710, 390, 325, 27))
        self.reset.setText(QtGui.QApplication.translate("Form", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.reset.setObjectName(_fromUtf8("reset"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.shiftUp, QtCore.SIGNAL(_fromUtf8("clicked()")), self.vc1.hide)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        self.changeTable.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Daily Change", None, QtGui.QApplication.UnicodeUTF8))
        self.riskTable.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Risk", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

